astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "openai"
  model_name: "models/text-embedding-3-small"

retriever:
  top_k: 4

llm:
  groq:
    provider: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
